sonar.projectKey=evat-data-science
sonar.projectName=EVAT Data Science
sonar.sources=main
sonar.tests=main/tests
sonar.exclusions=**/*.ipynb,**/__pycache__/**,main/tests/**
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
